### ISSUE TITLE
登录的时候， 账号和密码是必填吧

### ISSUE THREAD

**Issue by abigmiu** [chunshand/nest-template#2]
https://github.com/chunshand/nest-template/blob/753cdea3dacc7a7b6e93c2f53b76d40e4f96d56a/src/core/user/dto/login-user.dto.ts#L4

这里选填了。

用了swagger 的话， `PartialType` 应该从`swagger` 导入。 不然没有swaager对应字段说明

**Comment by chunshand** [comment]
这里确实是一个错误，已修改。PartialType()函数返回一个类型（类），并将所有输入类型设置为可选的。
